- dashboard only side bar
- likes and dislikes
- followers
- authenticated properly
- secure frontend bcrypt options ?



```sh
# MODELS
Comments	
    likes, dislikes, comment, date_created
    date_modified, author, post, parent

Messages
    thread, sender_user, reciever_user, body
    image, date_created, date_modified, is_read	

Thread models	
    user, reciever

Posts:
    body, image, date_created, date_modified
    author, likes, dislikes

Notifications
    notification_type, to_user ,from_user, post, 
    comment, thread, date_created, date_modified,
    user_has_seen

User profiles    
    user, name, bio, birth_date, location,
    picture, followers, date_created, date_modified	
```
	



"IntegrityError at /following/\nUNIQUE constraint failed: users_userfollowing.user_id\n\nRequest Method: POST\nRequest URL: http://localhost:8000/following/\nDjango Version: 4.1.4\nPython Executable: /Users/neo/.local/share/virtualenvs/backend-ka7GzyzF/bin/python3\nPython Version: 3.10.6\nPython Path: ['/Users/neo/.mine/projects/social_life/backend', '/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python310.zip', '/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10', '/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/lib-dynload', '/Users/neo/.local/share/virtualenvs/backend-ka7GzyzF/lib/python3.10/site-packages', '/opt/homebrew/opt/python-tk@3.10/libexec']\nServer time: Thu, 29 Dec 2022 19:25:09 +0000\nInstalled Applications:\n['django.contrib.admin',\n 'django.contrib.auth',\n 'django.contrib.contenttypes',\n 'django.contrib.sessions',\n 'django.contrib.messages',\n 'django.contrib.staticfiles',\n 'corsheaders',\n 'rest_framework',\n 'rest_framework_simplejwt.token_blacklist',\n 'users',\n 'social']\nInstalled Middleware:\n['corsheaders.middleware.CorsMiddleware',\n 'django.middleware.security.SecurityMiddleware',\n 'django.contrib.sessions.middleware.SessionMiddleware',\n 'django.middleware.common.CommonMiddleware',\n 'django.middleware.csrf.CsrfViewMiddleware',\n 'django.contrib.auth.middleware.AuthenticationMiddleware',\n 'django.contrib.messages.middleware.MessageMiddleware',\n 'django.middleware.clickjacking.XFrameOptionsMiddleware']\n\n\nTraceback (most recent call last):\n  File \"/Users/neo/.local/share/virtualenvs/backend-ka7GzyzF/lib/python3.10/site-packages/django/db/backends/utils.py\", line 89, in _execute\n    return self.cursor.execute(sql, params)\n  File \"/Users/neo/.local/share/virtualenvs/backend-ka7GzyzF/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py\", line 357, in execute\n    return Database.Cursor.execute(self, query, params)\n\nThe above exception (UNIQUE constraint failed: users_userfollowing.user_id) was the direct cause of the following exception:\n  File \"/Users/neo/.local/share/virtualenvs/backend-ka7GzyzF/lib/python3.10/site-packages/django/core/handlers/exception.py\", line 55, in inner\n    response = get_response(request)\n  File \"/Users/neo/.local/share/virtualenvs/backend-ka7GzyzF/lib/python3.10/site-packages/django/core/handlers/base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"/Users/neo/.local/share/virtualenvs/backend-ka7GzyzF/lib/python3.10/site-packages/django/views/decorators/csrf.py\", line 54, in wrapped_view\n    return view_func(*args, **kwargs)\n  File \"/Users/neo/.local/share/virtualenvs/backend-ka7GzyzF/lib/python3.10/site-packages/django/views/generic/base.py\", line 103, in view\n    return self.dispatch(request, *args, **kwargs)\n  File \"/Users/neo/.local/share/virtualenvs/backend-ka7GzyzF/lib/python3.10/site-packages/rest_framework/views.py\", line 509, in dispatch\n    response = self.handle_exception(exc)\n  File \"/Users/neo/.local/share/virtualenvs/backend-ka7GzyzF/lib/python3.10/site-packages/rest_framework/views.py\", line 469, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"/Users/neo/.local/share/virtualenvs/backend-ka7GzyzF/lib/python3.10/site-packages/rest_framework/views.py\", line 480, in raise_uncaught_exception\n    raise exc\n  File \"/Users/neo/.local/share/virtualenvs/backend-ka7GzyzF/lib/python3.10/site-packages/rest_framework/views.py\", line 506, in dispatch\n    response = handler(request, *args, **kwargs)\n  File \"/Users/neo/.local/share/virtualenvs/backend-ka7GzyzF/lib/python3.10/site-packages/rest_framework/generics.py\", line 242, in post\n    return self.create(request, *args, **kwargs)\n  File \"/Users/neo/.local/share/virtualenvs/backend-ka7GzyzF/lib/python3.10/site-packages/rest_framework/mixins.py\", line 19, in create\n    self.perform_create(serializer)\n  File \"/Users/neo/.local/share/virtualenvs/backend-ka7GzyzF/lib/python3.10/site-packages/rest_framework/mixins.py\", line 24, in perform_create\n    serializer.save()\n  File \"/Users/neo/.local/share/virtualenvs/backend-ka7GzyzF/lib/python3.10/site-packages/rest_framework/serializers.py\", line 212, in save\n    self.instance = self.create(validated_data)\n  File \"/Users/neo/.local/share/virtualenvs/backend-ka7GzyzF/lib/python3.10/site-packages/rest_framework/serializers.py\", line 962, in create\n    instance = ModelClass._default_manager.create(**validated_data)\n  File \"/Users/neo/.local/share/virtualenvs/backend-ka7GzyzF/lib/python3.10/site-packages/django/db/models/manager.py\", line 85, in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n  File \"/Users/neo/.local/share/virtualenvs/backend-ka7GzyzF/lib/python3.10/site-packages/django/db/models/query.py\", line 671, in create\n    obj.save(force_insert=True, using=self.db)\n  File \"/Users/neo/.local/share/virtualenvs/backend-ka7GzyzF/lib/python3.10/site-packages/django/db/models/base.py\", line 812, in save\n    self.save_base(\n  File \"/Users/neo/.local/share/virtualenvs/backend-ka7GzyzF/lib/python3.10/site-packages/django/db/models/base.py\", line 863, in save_base\n    updated = self._save_table(\n  File \"/Users/neo/.local/share/virtualenvs/backend-ka7GzyzF/lib/python3.10/site-packages/django/db/models/base.py\", line 1006, in _save_table\n    results = self._do_insert(\n  File \"/Users/neo/.local/share/virtualenvs/backend-ka7GzyzF/lib/python3.10/site-packages/django/db/models/base.py\", line 1047, in _do_insert\n    return manager._insert(\n  File \"/Users/neo/.local/share/virtualenvs/backend-ka7GzyzF/lib/python3.10/site-packages/django/db/models/manager.py\", line 85, in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n  File \"/Users/neo/.local/share/virtualenvs/backend-ka7GzyzF/lib/python3.10/site-packages/django/db/models/query.py\", line 1791, in _insert\n    return query.get_compiler(using=using).execute_sql(returning_fields)\n  File \"/Users/neo/.local/share/virtualenvs/backend-ka7GzyzF/lib/python3.10/site-packages/django/db/models/sql/compiler.py\", line 1660, in execute_sql\n    cursor.execute(sql, params)\n  File \"/Users/neo/.local/share/virtualenvs/backend-ka7GzyzF/lib/python3.10/site-packages/django/db/backends/utils.py\", line 103, in execute\n    return super().execute(sql, params)\n  File \"/Users/neo/.local/share/virtualenvs/backend-ka7GzyzF/lib/python3.10/site-packages/django/db/backends/utils.py\", line 67, in execute\n    return self._execute_with_wrappers(\n  File \"/Users/neo/.local/share/virtualenvs/backend-ka7GzyzF/lib/python3.10/site-packages/django/db/backends/utils.py\", line 80, in _execute_with_wrappers\n    return executor(sql, params, many, context)\n  File \"/Users/neo/.local/share/virtualenvs/backend-ka7GzyzF/lib/python3.10/site-packages/django/db/backends/utils.py\", line 84, in _execute\n    with self.db.wrap_database_errors:\n  File \"/Users/neo/.local/share/virtualenvs/backend-ka7GzyzF/lib/python3.10/site-packages/django/db/utils.py\", line 91, in __exit__\n    raise dj_exc_value.with_traceback(traceback) from exc_value\n  File \"/Users/neo/.local/share/virtualenvs/backend-ka7GzyzF/lib/python3.10/site-packages/django/db/backends/utils.py\", line 89, in _execute\n    return self.cursor.execute(sql, params)\n  File \"/Users/neo/.local/share/virtualenvs/backend-ka7GzyzF/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py\", line 357, in execute\n    return Database.Cursor.execute(self, query, params)\n\nException Type: IntegrityError at /following/\nException Value: UNIQUE constraint failed: users_userfollowing.user_id\nRaised during: users.views.UserFollowingList\nRequest information:\nUSER: neo\n\nGET: No GET data\n\nPOST: No POST data\n\nFILES: No FILES data\n\nCOOKIES: No cookie data\n\nMETA:\nCONTENT_LENGTH = '29'\nCONTENT_TYPE = 'application/json'\nDJANGO_SETTINGS_MODULE = 'social_django.settings'\nGATEWAY_INTERFACE = 'CGI/1.1'\nHOME = '/Users/neo'\nHOMEBREW_CELLAR = '/opt/homebrew/Cellar'\nHOMEBREW_PREFIX = '/opt/homebrew'\nHOMEBREW_REPOSITORY = '/opt/homebrew'\nHTTP_ACCEPT = 'application/json'\nHTTP_ACCEPT_ENCODING = 'gzip, deflate, br'\nHTTP_ACCEPT_LANGUAGE = 'en-US,en;q=0.9'\nHTTP_AUTHORIZATION = 'JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjcyMzQ3OTAzLCJpYXQiOjE2NzIzNDA3MDMsImp0aSI6IjdhMjY0MGZjNzRiZTQ2NjZhZTI2NzNkMjBlYjMzNDY3IiwidXNlcm5hbWUiOiJuZW8ifQ.S0VqliHUWIHE7b9xmbekU7Kc8ZIOxAcDhv98AeVkxkc'\nHTTP_CONNECTION = 'keep-alive'\nHTTP_HOST = 'localhost:8000'\nHTTP_ORIGIN = 'http://localhost:8000'\nHTTP_REFERER = 'http://localhost:8000/profile/1'\nHTTP_SEC_CH_UA = '\"Not?A_Brand\";v=\"8\", \"Chromium\";v=\"108\", \"Google Chrome\";v=\"108\"'\nHTTP_SEC_CH_UA_MOBILE = '?0'\nHTTP_SEC_CH_UA_PLATFORM = '\"macOS\"'\nHTTP_SEC_FETCH_DEST = 'empty'\nHTTP_SEC_FETCH_MODE = 'cors'\nHTTP_SEC_FETCH_SITE = 'same-origin'\nHTTP_USER_AGENT = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36'\nINFOPATH = '/opt/homebrew/share/info:'\nLANG = 'en_US.UTF-8'\nLESS = '-R'\nLOGNAME = 'neo'\nLSCOLORS = 'Gxfxcxdxbxegedabagacad'\nLaunchInstanceID = '867D4C6F-AD65-4DA5-BAFC-C6C6574A6869'\nMANPATH = '/opt/homebrew/share/man::'\nOLDPWD = '/Users/neo/.mine/projects/social_life/backend'\nPAGER = 'less'\nPATH = '/Users/neo/.local/share/virtualenvs/backend-ka7GzyzF/bin:/opt/homebrew/opt/libpq/bin:/Users/neo/opt/anaconda3/bin:/opt/homebrew/opt/libpq/bin:/Users/neo/opt/anaconda3/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools'\nPATH_INFO = '/following/'\nPIPENV_ACTIVE = '1'\nPIP_DISABLE_PIP_VERSION_CHECK = '1'\nPIP_PYTHON_PATH = '/opt/homebrew/opt/python@3.10/bin/python3.10'\nPS1 = '(backend) %(?:%{\\x1b[01;32m%}➜ :%{\\x1b[01;31m%}➜ ) %{$fg[cyan]%}%c%{$reset_color%} $(git_prompt_info)'\nPWD = '/Users/neo/.mine/projects/social_life/backend'\nPYTHONDONTWRITEBYTECODE = '1'\nQUERY_STRING = ''\nREMOTE_ADDR = '127.0.0.1'\nREMOTE_HOST = ''\nREQUEST_METHOD = 'POST'\nRUN_MAIN = 'true'\nSCRIPT_NAME = ''\nSECURITYSESSIONID = '186b1'\nSERVER_NAME = '1.0.0.127.in-addr.arpa'\nSERVER_PORT = '8000'\nSERVER_PROTOCOL = 'HTTP/1.1'\nSERVER_SOFTWARE = 'WSGIServer/0.2'\nSHELL = '/bin/zsh'\nSHLVL = '2'\nSSH_AUTH_SOCK = '/private/tmp/com.apple.launchd.hT86qX3RMg/Listeners'\nTERM = 'xterm-256color'\nTERM_PROGRAM = 'Apple_Terminal'\nTERM_PROGRAM_VERSION = '445'\nTERM_SESSION_ID = '2655F0F7-EBD6-422C-8298-C060266EBCBF'\nTMPDIR = '/var/folders/3y/0qmw69657x5_wmjk3940h_d40000gn/T/'\nTZ = 'UTC'\nUSER = 'neo'\nVIRTUAL_ENV = '/Users/neo/.local/share/virtualenvs/backend-ka7GzyzF'\nXPC_FLAGS = '0x0'\nXPC_SERVICE_NAME = '0'\nZSH = '/Users/neo/.oh-my-zsh'\n_ = '/Users/neo/.local/share/virtualenvs/backend-ka7GzyzF/bin/python3'\n__CFBundleIdentifier = 'com.apple.Terminal'\n__CF_USER_TEXT_ENCODING = '0x1F5:0x0:0x0'\nwsgi.errors = <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>\nwsgi.file_wrapper = <class 'wsgiref.util.FileWrapper'>\nwsgi.input = <django.core.handlers.wsgi.LimitedStream object at 0x1034ca530>\nwsgi.multiprocess = False\nwsgi.multithread = True\nwsgi.run_once = False\nwsgi.url_scheme = 'http'\nwsgi.version = '(1, 0)'\n\nSettings:\nUsing settings module social_django.settings\nABSOLUTE_URL_OVERRIDES = {}\nADMINS = []\nALLOWED_HOSTS = ['*']\nAPPEND_SLASH = True\nAUTHENTICATION_BACKENDS = ['django.contrib.auth.backends.ModelBackend']\nAUTH_PASSWORD_VALIDATORS = '********************'\nAUTH_USER_MODEL = 'users.User'\nBASE_DIR = PosixPath('/Users/neo/.mine/projects/social_life/backend')\nCACHES = {'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}}\nCACHE_MIDDLEWARE_ALIAS = 'default'\nCACHE_MIDDLEWARE_KEY_PREFIX = '********************'\nCACHE_MIDDLEWARE_SECONDS = 600\nCORS_ALLOW_ALL_ORIGINS = True\nCSRF_COOKIE_AGE = 31449600\nCSRF_COOKIE_DOMAIN = None\nCSRF_COOKIE_HTTPONLY = False\nCSRF_COOKIE_MASKED = False\nCSRF_COOKIE_NAME = 'csrftoken'\nCSRF_COOKIE_PATH = '/'\nCSRF_COOKIE_SAMESITE = 'Lax'\nCSRF_COOKIE_SECURE = False\nCSRF_FAILURE_VIEW = 'django.views.csrf.csrf_failure'\nCSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN'\nCSRF_TRUSTED_ORIGINS = []\nCSRF_USE_SESSIONS = False\nDATABASES = {'default': {'ENGINE': 'django.db.backends.sqlite3', 'NAME': PosixPath('/Users/neo/.mine/projects/social_life/backend/db.sqlite3'), 'ATOMIC_REQUESTS': False, 'AUTOCOMMIT': True, 'CONN_MAX_AGE': 0, 'CONN_HEALTH_CHECKS': False, 'OPTIONS': {}, 'TIME_ZONE': None, 'USER': '', 'PASSWORD': '********************', 'HOST': '', 'PORT': '', 'TEST': {'CHARSET': None, 'COLLATION': None, 'MIGRATE': True, 'MIRROR': None, 'NAME': None}}}\nDATABASE_ROUTERS = []\nDATA_UPLOAD_MAX_MEMORY_SIZE = 2621440\nDATA_UPLOAD_MAX_NUMBER_FIELDS = 1000\nDATETIME_FORMAT = 'N j, Y, P'\nDATETIME_INPUT_FORMATS = ['%Y-%m-%d %H:%M:%S', '%Y-%m-%d %H:%M:%S.%f', '%Y-%m-%d %H:%M', '%m/%d/%Y %H:%M:%S', '%m/%d/%Y %H:%M:%S.%f', '%m/%d/%Y %H:%M', '%m/%d/%y %H:%M:%S', '%m/%d/%y %H:%M:%S.%f', '%m/%d/%y %H:%M']\nDATE_FORMAT = 'N j, Y'\nDATE_INPUT_FORMATS = ['%Y-%m-%d', '%m/%d/%Y', '%m/%d/%y', '%b %d %Y', '%b %d, %Y', '%d %b %Y', '%d %b, %Y', '%B %d %Y', '%B %d, %Y', '%d %B %Y', '%d %B, %Y']\nDEBUG = True\nDEBUG_PROPAGATE_EXCEPTIONS = False\nDECIMAL_SEPARATOR = '.'\nDEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'\nDEFAULT_CHARSET = 'utf-8'\nDEFAULT_EXCEPTION_REPORTER = 'django.views.debug.ExceptionReporter'\nDEFAULT_EXCEPTION_REPORTER_FILTER = 'django.views.debug.SafeExceptionReporterFilter'\nDEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'\nDEFAULT_FROM_EMAIL = 'webmaster@localhost'\nDEFAULT_INDEX_TABLESPACE = ''\nDEFAULT_TABLESPACE = ''\nDISALLOWED_USER_AGENTS = []\nEMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'\nEMAIL_HOST = 'localhost'\nEMAIL_HOST_PASSWORD = '********************'\nEMAIL_HOST_USER = ''\nEMAIL_PORT = 25\nEMAIL_SSL_CERTFILE = None\nEMAIL_SSL_KEYFILE = '********************'\nEMAIL_SUBJECT_PREFIX = '[Django] '\nEMAIL_TIMEOUT = None\nEMAIL_USE_LOCALTIME = False\nEMAIL_USE_SSL = False\nEMAIL_USE_TLS = False\nFILE_UPLOAD_DIRECTORY_PERMISSIONS = None\nFILE_UPLOAD_HANDLERS = ['django.core.files.uploadhandler.MemoryFileUploadHandler', 'django.core.files.uploadhandler.TemporaryFileUploadHandler']\nFILE_UPLOAD_MAX_MEMORY_SIZE = 2621440\nFILE_UPLOAD_PERMISSIONS = 416\nFILE_UPLOAD_TEMP_DIR = None\nFIRST_DAY_OF_WEEK = 0\nFIXTURE_DIRS = []\nFORCE_SCRIPT_NAME = None\nFORMAT_MODULE_PATH = None\nFORM_RENDERER = 'django.forms.renderers.DjangoTemplates'\nIGNORABLE_404_URLS = []\nINSTALLED_APPS = ['django.contrib.admin', 'django.contrib.auth', 'django.contrib.contenttypes', 'django.contrib.sessions', 'django.contrib.messages', 'django.contrib.staticfiles', 'corsheaders', 'rest_framework', 'rest_framework_simplejwt.token_blacklist', 'users', 'social']\nINTERNAL_IPS = []\nLANGUAGES = [('af', 'Afrikaans'), ('ar', 'Arabic'), ('ar-dz', 'Algerian Arabic'), ('ast', 'Asturian'), ('az', 'Azerbaijani'), ('bg', 'Bulgarian'), ('be', 'Belarusian'), ('bn', 'Bengali'), ('br', 'Breton'), ('bs', 'Bosnian'), ('ca', 'Catalan'), ('cs', 'Czech'), ('cy', 'Welsh'), ('da', 'Danish'), ('de', 'German'), ('dsb', 'Lower Sorbian'), ('el', 'Greek'), ('en', 'English'), ('en-au', 'Australian English'), ('en-gb', 'British English'), ('eo', 'Esperanto'), ('es', 'Spanish'), ('es-ar', 'Argentinian Spanish'), ('es-co', 'Colombian Spanish'), ('es-mx', 'Mexican Spanish'), ('es-ni', 'Nicaraguan Spanish'), ('es-ve', 'Venezuelan Spanish'), ('et', 'Estonian'), ('eu', 'Basque'), ('fa', 'Persian'), ('fi', 'Finnish'), ('fr', 'French'), ('fy', 'Frisian'), ('ga', 'Irish'), ('gd', 'Scottish Gaelic'), ('gl', 'Galician'), ('he', 'Hebrew'), ('hi', 'Hindi'), ('hr', 'Croatian'), ('hsb', 'Upper Sorbian'), ('hu', 'Hungarian'), ('hy', 'Armenian'), ('ia', 'Interlingua'), ('id', 'Indonesian'), ('ig', 'Igbo'), ('io', 'Ido'), ('is', 'Icelandic'), ('it', 'Italian'), ('ja', 'Japanese'), ('ka', 'Georgian'), ('kab', 'Kabyle'), ('kk', 'Kazakh'), ('km', 'Khmer'), ('kn', 'Kannada'), ('ko', 'Korean'), ('ky', 'Kyrgyz'), ('lb', 'Luxembourgish'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('mk', 'Macedonian'), ('ml', 'Malayalam'), ('mn', 'Mongolian'), ('mr', 'Marathi'), ('ms', 'Malay'), ('my', 'Burmese'), ('nb', 'Norwegian Bokmål'), ('ne', 'Nepali'), ('nl', 'Dutch'), ('nn', 'Norwegian Nynorsk'), ('os', 'Ossetic'), ('pa', 'Punjabi'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('pt-br', 'Brazilian Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('sq', 'Albanian'), ('sr', 'Serbian'), ('sr-latn', 'Serbian Latin'), ('sv', 'Swedish'), ('sw', 'Swahili'), ('ta', 'Tamil'), ('te', 'Telugu'), ('tg', 'Tajik'), ('th', 'Thai'), ('tk', 'Turkmen'), ('tr', 'Turkish'), ('tt', 'Tatar'), ('udm', 'Udmurt'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('uz', 'Uzbek'), ('vi', 'Vietnamese'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese')]\nLANGUAGES_BIDI = ['he', 'ar', 'ar-dz', 'fa', 'ur']\nLANGUAGE_CODE = 'en-us'\nLANGUAGE_COOKIE_AGE = None\nLANGUAGE_COOKIE_DOMAIN = None\nLANGUAGE_COOKIE_HTTPONLY = False\nLANGUAGE_COOKIE_NAME = 'django_language'\nLANGUAGE_COOKIE_PATH = '/'\nLANGUAGE_COOKIE_SAMESITE = None\nLANGUAGE_COOKIE_SECURE = False\nLOCALE_PATHS = []\nLOGGING = {}\nLOGGING_CONFIG = 'logging.config.dictConfig'\nLOGIN_REDIRECT_URL = '/accounts/profile/'\nLOGIN_URL = '/accounts/login/'\nLOGOUT_REDIRECT_URL = None\nMANAGERS = []\nMEDIA_ROOT = '/Users/neo/.mine/projects/social_life/backend/media'\nMEDIA_URL = '/media/'\nMESSAGE_STORAGE = 'django.contrib.messages.storage.fallback.FallbackStorage'\nMIDDLEWARE = ['corsheaders.middleware.CorsMiddleware', 'django.middleware.security.SecurityMiddleware', 'django.contrib.sessions.middleware.SessionMiddleware', 'django.middleware.common.CommonMiddleware', 'django.middleware.csrf.CsrfViewMiddleware', 'django.contrib.auth.middleware.AuthenticationMiddleware', 'django.contrib.messages.middleware.MessageMiddleware', 'django.middleware.clickjacking.XFrameOptionsMiddleware']\nMIGRATION_MODULES = {}\nMONTH_DAY_FORMAT = 'F j'\nNUMBER_GROUPING = 0\nPASSWORD_HASHERS = '********************'\nPASSWORD_RESET_TIMEOUT = '********************'\nPREPEND_WWW = False\nREST_FRAMEWORK = {'DEFAULT_PERMISSION_CLASSES': ['rest_framework.permissions.AllowAny', 'rest_framework.permissions.IsAuthenticated'], 'DEFAULT_AUTHENTICATION_CLASSES': ('rest_framework.authentication.TokenAuthentication', 'rest_framework_simplejwt.authentication.JWTAuthentication')}\nROOT_URLCONF = 'social_django.urls'\nSECRET_KEY = '********************'\nSECRET_KEY_FALLBACKS = '********************'\nSECURE_CONTENT_TYPE_NOSNIFF = True\nSECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'\nSECURE_HSTS_INCLUDE_SUBDOMAINS = False\nSECURE_HSTS_PRELOAD = False\nSECURE_HSTS_SECONDS = 0\nSECURE_PROXY_SSL_HEADER = None\nSECURE_REDIRECT_EXEMPT = []\nSECURE_REFERRER_POLICY = 'same-origin'\nSECURE_SSL_HOST = None\nSECURE_SSL_REDIRECT = False\nSERVER_EMAIL = 'root@localhost'\nSESSION_CACHE_ALIAS = 'default'\nSESSION_COOKIE_AGE = 1209600\nSESSION_COOKIE_DOMAIN = None\nSESSION_COOKIE_HTTPONLY = True\nSESSION_COOKIE_NAME = 'sessionid'\nSESSION_COOKIE_PATH = '/'\nSESSION_COOKIE_SAMESITE = 'Lax'\nSESSION_COOKIE_SECURE = False\nSESSION_ENGINE = 'django.contrib.sessions.backends.db'\nSESSION_EXPIRE_AT_BROWSER_CLOSE = False\nSESSION_FILE_PATH = None\nSESSION_SAVE_EVERY_REQUEST = False\nSESSION_SERIALIZER = 'django.contrib.sessions.serializers.JSONSerializer'\nSETTINGS_MODULE = 'social_django.settings'\nSHORT_DATETIME_FORMAT = 'm/d/Y P'\nSHORT_DATE_FORMAT = 'm/d/Y'\nSIGNING_BACKEND = 'django.core.signing.TimestampSigner'\nSILENCED_SYSTEM_CHECKS = []\nSIMPLE_JWT = {'ACCESS_TOKEN_LIFETIME': '********************', 'REFRESH_TOKEN_LIFETIME': '********************', 'ROTATE_REFRESH_TOKENS': '********************', 'BLACKLIST_AFTER_ROTATION': True, 'ALGORITHM': 'HS256', 'SIGNING_KEY': '********************', 'VERIFYING_KEY': '********************', 'AUTH_HEADER_TYPES': ('JWT',), 'USER_ID_FIELD': 'username', 'USER_ID_CLAIM': 'username', 'AUTH_TOKEN_CLASSES': '********************', 'TOKEN_TYPE_CLAIM': '********************'}\nSTATICFILES_DIRS = ['/Users/neo/.mine/projects/social_life/backend/build/static']\nSTATICFILES_FINDERS = ['django.contrib.staticfiles.finders.FileSystemFinder', 'django.contrib.staticfiles.finders.AppDirectoriesFinder']\nSTATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'\nSTATIC_ROOT = '/Users/neo/.mine/projects/social_life/backend/static'\nSTATIC_URL = '/static/'\nTEMPLATES = [{'BACKEND': 'django.template.backends.django.DjangoTemplates', 'DIRS': ['/Users/neo/.mine/projects/social_life/backend/build'], 'APP_DIRS': True, 'OPTIONS': {'context_processors': ['django.template.context_processors.debug', 'django.template.context_processors.request', 'django.contrib.auth.context_processors.auth', 'django.contrib.messages.context_processors.messages']}}]\nTEST_NON_SERIALIZED_APPS = []\nTEST_RUNNER = 'django.test.runner.DiscoverRunner'\nTHOUSAND_SEPARATOR = ','\nTIME_FORMAT = 'P'\nTIME_INPUT_FORMATS = ['%H:%M:%S', '%H:%M:%S.%f', '%H:%M']\nTIME_ZONE = 'UTC'\nUSE_DEPRECATED_PYTZ = False\nUSE_I18N = True\nUSE_L10N = True\nUSE_THOUSAND_SEPARATOR = False\nUSE_TZ = True\nUSE_X_FORWARDED_HOST = False\nUSE_X_FORWARDED_PORT = False\nWSGI_APPLICATION = 'social_django.wsgi.application'\nX_FRAME_OPTIONS = 'DENY'\nYEAR_MONTH_FORMAT = 'F Y'\n\n\nYou’re seeing this error because you have DEBUG = True in your\nDjango settings file. Change that to False, and Django will\ndisplay a standard page generated by the handler for this status code.\n\n"